### ISSUE TITLE
Practica Architect 

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-3-practica-architect-Heidi-19#1]

**Comment by Heidi-19** [comment]
[Reporte de practica Architec_Heidi Lucy Bautista Sanjuan.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-Heidi-19/files/9470789/Reporte.de.practica.Architec_Heidi.Lucy.Bautista.Sanjuan.pdf)

**Comment by JudithReynaCS** [comment]
Calificacion:20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
